name: aewallet
description: Fully decentralized and cryptocurrency non-custodial hot wallet that enables you to safely manage assets on Layer 1 Archethic blockchain.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.3.7+515

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  # Beautiful animations inspired on Animate.css, every animation is a widget that contains default but customizable values that look attractive.
  animate_do: ^3.0.2

  # Retrieve version and url for local app update against store app Android and iOS
  app_version_update: ^4.0.1

  archethic_dapp_framework_flutter: ^0.0.0
  #archethic_dapp_framework_flutter:
  #  git:
  #    url: https://github.com/archethic-foundation/archethic-dapp-framework-flutter.git
  #    ref: main
  #archethic_dapp_framework_flutter:
  #  path: ../archethic-dapp-framework-flutter

  # Archethic dart library for Flutter based on Official Archethic Javascript library for Node and Browser
  archethic_lib_dart: ^3.3.0
  #archethic_lib_dart:
  #  git:
  #    url: https://github.com/archethic-foundation/libdart.git
  #    ref: dev

  # Archethic Messaging Dart SDK
  archethic_messaging_lib_dart: ^0.0.0
  #archethic_messaging_lib_dart:
  #  git:
  #    url: https://github.com/archethic-foundation/messaging_dart_sdk.git
  #    ref: main

  # An ASN1 parser library for Dart. Encodes / decodes from ASN1 Objects to BER bytes
  asn1lib: ^1.5.0

  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0

  # A flutter package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
  badges: ^3.0.3

  # A flutter plugin for scanning 2D barcodes and QRCodes via camera
  barcode_scan2: ^4.2.3

  # Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
  bip39_mnemonic: ^3.0.6

  # Bottom bar helps create an optimized bottom navigation bar with beautiful animations
  bottom_bar: ^2.0.3

  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.2.3

  # A fakeable wrapper for dart:core clock APIs
  clock: ^1.1.1

  # Dart package that provides simple access to the CoinGecko API (Version 3)
  coingecko_api: ^1.1.1+1

  # Collections and utilities functions and classes related to collections.
  collection: ^1.18.0

  # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^5.0.2

  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.1.1

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.3

  # The decimal package allows you to deal with decimal numbers without losing precision
  decimal: ^2.3.3

  # A RPC-via-deeplink communication library coded in Dart. This is dedicated to Flutter mobile applications (iOS / Android).
  deeplink_rpc: ^1.0.6

  # EventTaxi could be used to send events through different layers of the application decoupled from the architecture
  event_taxi: ^1.0.0

  # Dart package to decode Exif data from tiff, jpeg and heic files.
  exif: ^3.1.4

  # A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
  file_picker: ^6.2.0

  # A package to get humanized file sizes. Translate raw file size into human readable strings
  filesize: ^2.0.1

  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps.
  firebase_core: ^2.27.0

  # A package to use FCM
  firebase_messaging: ^14.7.19

  # A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
  fl_chart: ^0.66.2

  flutter:
    sdk: flutter

  # Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
  flutter_animate: ^4.2.0+1

  # A flutter implementation of React hooks. It adds a new kind of widget with enhanced code reuse
  flutter_hooks: ^0.20.0

  # A WebView
  flutter_inappwebview: ^6.0.0

  # Flutter jailbreak and root detection plugin. This plugin wraps Rootbeer for use on Android and DTTJailbreakDetection for use on iOS.
  flutter_jailbreak_detection: ^1.10.0

  # Makes in-text links clickable
  flutter_linkify: ^6.0.0

  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^9.7.1

  flutter_localizations:
    sdk: flutter

  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.3.10

  # State management
  flutter_riverpod: ^2.5.1

  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android
  flutter_secure_storage: ^9.0.0

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files
  flutter_svg: ^2.0.6

  # A Flutter plugin to vibrate the device
  flutter_vibrate: ^1.3.0

  # Annotations for freezed
  freezed_annotation: ^2.4.1

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.2.0

  # Ghost CMS API client that closely follows the official implementation
  ghost: ^2.0.3

  # A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more
  go_router: ^13.2.0

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^1.2.0

  # Convert all *.svg icons from dir to icon-font (.ttf) and generates flutter compatible dart class
  icon_font_generator: ^3.2.0

  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera
  image_picker: ^1.0.2

  # ListViews pagination
  infinite_scroll_pagination: ^4.0.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.18.1

  # Utilities to write a client or server using the JSON-RPC 2.0 spec.
  json_rpc_2: ^3.0.2

  # JSON Schema implementation in Dart
  json_schema: ^5.1.2

  # Ledger dart library for Flutter. This library aims to provide a easy way to communicate with Ledger devices.
  ledger_dart_lib: ^0.1.2

  lit_starfield: ^0.1.1

  # Loading animation or loading spiner or loader. It's used to show loading animation when the app is in loading state or something is processing for uncertain time.
  loading_animation_widget: ^1.2.0+4

  # Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern
  local_auth: ^2.2.0

  # Using Official Material Symbols Icons variable fonts
  material_symbols_icons: ^4.2719.1

  # Get Mime Types, Extensions, Compressible for Dart and Flutter. Inspired from IANA Database
  mime_dart: ^3.0.0

  # Flutter plugin for accessing the NFC features on Android and iOS.
  nfc_manager: ^3.3.0

  # A pure flutter toast library Support custom style/widget. Easy to use. You can use this library to achieve the same effect as Android toast
  oktoast: ^3.3.1

  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android
  package_info_plus: ^4.2.0

  # A basic password strength estimator for Dart. Considers the length of the password, used characters, and whether or not the password appears in the top 10,000 most used passwords.
  password_strength: ^0.2.0

  # A string-based path manipulation library. All of the path operations you know and love, with solid support for Windows, POSIX (Linux and Mac OS X), and the web.
  path: ^1.9.0

  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.1.0

  # Flutter plugin to render & show PDF pages as images on Web, MacOS, Windows, Android and iOS.
  pdfx: ^2.6.0

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library
  pointycastle: ^3.7.0

  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter
  qr_flutter: ^4.1.0

  # Quiver is a set of utility libraries for Dart that makes using many Dart libraries easier and more convenient, or adds additional functionality
  quiver: ^3.2.1

  # A package exposing annotations for riverpod_generator
  riverpod_annotation: ^2.3.5

  # RxDart is an implementation of the popular reactiveX api for asynchronous programming, leveraging the native Dart Streams api.
  rxdart: ^0.27.7

  # Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  share_plus: ^7.1.0

  # Dartlang port of socket.io-client for web, flutter, dartvm to use
  socket_io_client: ^2.0.3+1

  stream_channel: any

  # Lock mechanism to prevent concurrent access to asynchronous code.
  synchronized: ^3.1.0

  # Tuple data structure
  tuple: ^2.0.1

  # Unicode 8.0 Normalization - NFC, NFD, NFKC, NFKD
  unorm_dart: ^0.2.0

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.2.5

  # RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)
  uuid: ^4.3.3

  # String validation and sanitization for Dart
  validators: ^3.0.0

  # RPC server
  web_socket_channel: ^2.4.3

  webview_flutter: ^4.7.0

  # This plugin allows Flutter desktop apps to resizing and repositioning the window.
  window_manager: ^0.3.8

  # Yubico dart library for Dart/Flutter
  yubidart: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.2
  hive_generator: ^2.0.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.0
  # A command-line tool that create Msix installer from your flutter windows-build files.
  msix: ^3.16.7
  # Simple yet powerful Flutter-native UI testing framework eliminating limitations of flutter_test, integration_test, and flutter_driver.
  patrol: ^3.5.2
  # A code generator for Riverpod. This both simplifies the syntax empowers it, such as allowing stateful hot-reload.
  riverpod_generator: ^2.3.11

msix_config:
  display_name: Archethic Wallet
  publisher_display_name: Archethic Technologies SARL
  identity_name: ArchethicTechnologiesSARL.ArchethicWallet
  publisher: CN=9687A561-7463-4BA7-BD4D-A04574BAF854
  msix_version: 2.36.512.0
  icons_background_color: "#000000"
  languages: en-us
  store: true
  logo_path: windows/icons/Icon-512.png
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: "internetClient,webcam,USB"

flutter_launcher_icons:
  image_path_android: "assets/themes/archethic/logo_crystal.png"
  image_path_ios: "assets/themes/archethic/logo_crystal.png"
  android: true
  ios: true
  image_path: "assets/themes/archethic/logo_crystal.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#000000"
  web:
    generate: true
    image_path: "assets/themes/archethic/icon-1024x1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/themes/archethic/icon-1024x1024.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/themes/archethic/icon-1024x1024.png"

# The following section is specific to Flutter.
flutter:
  generate: true

  assets:
    - assets/ssl/isrg-root-x1.pem
    - assets/ssl/r3.pem
    - assets/icons/
    - assets/icons/currency/
    - assets/icons/languages/
    - assets/icons/menu/
    - assets/icons/txInfos/
    - assets/buy/
    - assets/themes/archethic/
    - lib/model/json-schemas/nft/opensea.json
    - lib/model/json-schemas/nft/archethic.json
    - lib/domain/repositories/tokens/verified_tokens.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: UiIcons
      fonts:
        - asset: assets/fonts/ui_icons.ttf
    - family: PPTelegraf
      fonts:
        - asset: assets/fonts/PPTelegraf-Ultralight.otf
          weight: 200
        - asset: assets/fonts/PPTelegraf-Light.otf
          weight: 300
        - asset: assets/fonts/PPTelegraf-Regular.otf
          weight: 400
        - asset: assets/fonts/PPTelegraf-Medium.otf
          weight: 500
        - asset: assets/fonts/PPTelegraf-Semibold.otf
          weight: 600
        - asset: assets/fonts/PPTelegraf-Bold.otf
          weight: 700
        - asset: assets/fonts/PPTelegraf-Ultrabold.otf
          weight: 800
        - asset: assets/fonts/PPTelegraf-Black.otf
          weight: 900

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
