name: aeroot
description: A place for all the DApps to live.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.3+203

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  core:
    path: packages/core

  core_ui:
    path: packages/core_ui

  aeuniverse:
    path: packages/aeuniverse

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.1.1
  
dev_dependencies:
  flutter_lints: ^1.0.4
  # Automatically organize your dart imports
  import_sorter: 
    git:
      url: https://github.com/redDwarf03/import_sorter.git
      ref: master
  # Integration Tests
  integration_test:
    sdk: flutter
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl_generator: ^0.2.1
  # A command-line tool that create Msix installer from your flutter windows-build files.
  msix: ^2.8.15

flutter_icons:
  android: true
  ios: true

msix_config:
  display_name: ARCHEthic Wallet
  publisher_display_name: ARCHEthic Foundation
  identity_name: testnet.archethic.net
  msix_version: 0.1.8.0
  icons_background_color: "#000000"
  logo_path: windows/icons/Icon-512.png
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: "internetClient,webcam,USB,Bluetooth"
  output_name: ARCHEthicWallet

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true