name: aewallet
description: Fully decentralized and cryptocurrency non-custodial hot wallet that enables you to safely manage assets on Layer 1 Archethic blockchain.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.1.1+444

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: "3.10.5"

dependencies:
  # Beautiful animations inspired on Animate.css, every animation is a widget that contains default but customizable values that look attractive.
  animate_do: ^3.0.2

  # Retrieve version and url for local app update against store app Android and iOS
  app_version_update: ^3.1.0

  # Archethic dart library for Flutter based on Official Archethic Javascript library for Node and Browser
  #archethic_lib_dart: ^3.1.1
  archethic_lib_dart:
    git:
      url: https://github.com/archethic-foundation/libdart.git
      ref: sc_test_mi

  # An ASN1 parser library for Dart. Encodes / decodes from ASN1 Objects to BER bytes
  asn1lib: ^1.4.0

  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0

  # A flutter package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
  badges: ^3.0.3

  # A flutter plugin for scanning 2D barcodes and QRCodes via camera
  barcode_scan2: ^4.2.3

  # Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
  bip39_mnemonic: ^3.0.6

  # Bottom bar helps create an optimized bottom navigation bar with beautiful animations
  bottom_bar: ^2.0.3

  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.2.3

  # A fakeable wrapper for dart:core clock APIs
  clock: ^1.1.1

  # Dart package that provides simple access to the CoinGecko API (Version 3)
  coingecko_api: ^1.1.1+1

  # Collections and utilities functions and classes related to collections.
  collection: ^1.17.0

  # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^3.0.3

  # Encapsulates TabController, TabBar and TabBarView into a single customizable Widget.
  contained_tab_bar_view: ^0.8.0

  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.1.1

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.3

  # The decimal package allows you to deal with decimal numbers without losing precision
  decimal: ^2.3.2

  # A RPC-via-deeplink communication library coded in Dart. This is dedicated to Flutter mobile applications (iOS / Android).
  deeplink_rpc: ^1.0.4

  # GridView with dynamic height. No need to specify aspectRatio to the grid.
  dynamic_height_grid_view: ^0.0.3

  # EventTaxi could be used to send events through different layers of the application decoupled from the architecture
  event_taxi: ^1.0.0

  # Dart package to decode Exif data from tiff, jpeg and heic files.
  exif: ^3.1.4

  # A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
  expandable: ^5.0.1

  # A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
  file_picker: ^5.2.7

  # A package to get humanized file sizes. Translate raw file size into human readable strings
  filesize: ^2.0.1

  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps.
  firebase_core: ^2.14.0

  # A package to use FCM
  firebase_messaging: ^14.6.3

  # A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
  fl_chart: ^0.61.0

  flutter:
    sdk: flutter

  # Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
  flutter_animate: ^4.1.1+1

  # Flutter jailbreak and root detection plugin. This plugin wraps Rootbeer for use on Android and DTTJailbreakDetection for use on iOS.
  flutter_jailbreak_detection: ^1.10.0

  # Makes in-text links clickable
  flutter_linkify: ^6.0.0

  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^9.7.1

  flutter_localizations:
    sdk: flutter

  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.3.0

  # State management
  flutter_riverpod: ^2.3.6

  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android
  flutter_secure_storage: ^8.0.0

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files
  flutter_svg: ^2.0.6

  # A Flutter plugin to vibrate the device
  flutter_vibrate: ^1.3.0

  # Annotations for freezed
  freezed_annotation: ^2.2.0

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.2.0

  # Ghost CMS API client that closely follows the official implementation
  ghost: ^2.0.2

  # PhoenixSocket provides a feature-complete implementation of Phoenix Sockets, using a single API based on StreamChannels compatible with any deployment of Flutter.
  gql: ^0.14.0

  # Gradient borders for inputs and containers. Borders package integrated with a basic flutter widgets as a container and input decorations. Easy in use, platform independent.
  gradient_borders: ^1.0.0

  graphql_flutter: ^5.1.2

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^0.13.5

  # Convert all *.svg icons from dir to icon-font (.ttf) and generates flutter compatible dart class
  icon_font_generator: ^3.2.0

  # Iconsax for flutter (1000+ icons 6 diferent styles, total 6000+ icons).
  iconsax: ^0.0.8

  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera
  image_picker: ^0.8.6+1

  # ListViews pagination
  infinite_scroll_pagination: ^3.2.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: any

  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.8.0

  # Ledger dart library for Flutter. This library aims to provide a easy way to communicate with Ledger devices.
  json_rpc_2: ^3.0.2
  ledger_dart_lib: ^0.1.2

  # Loading animation or loading spiner or loader. It's used to show loading animation when the app is in loading state or something is processing for uncertain time.
  loading_animation_widget: ^1.2.0+4

  # Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern
  local_auth: ^2.1.6

  # Get Mime Types, Extensions, Compressible for Dart and Flutter. Inspired from IANA Database
  mime_dart: ^3.0.0

  # Flutter plugin for accessing the NFC features on Android and iOS.
  nfc_manager: ^3.2.0

  # A pure flutter toast library Support custom style/widget. Easy to use. You can use this library to achieve the same effect as Android toast
  oktoast: ^3.3.1

  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android
  package_info_plus: ^3.0.2

  # Customizable indicators for your PageViews.
  page_view_indicators: ^2.0.0

  # A basic password strength estimator for Dart. Considers the length of the password, used characters, and whether or not the password appears in the top 10,000 most used passwords.
  password_strength: ^0.2.0

  # A string-based path manipulation library. All of the path operations you know and love, with solid support for Windows, POSIX (Linux and Mac OS X), and the web.
  path: ^1.8.3

  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.0.14

  # Flutter plugin to render & show PDF pages as images on Web, MacOS, Windows, Android and iOS.
  pdfx: 2.2.0

  # PhoenixSocket provides a feature-complete implementation of Phoenix Sockets, using a single API based on StreamChannels compatible with any deployment of Flutter
  phoenix_socket: ^0.6.2

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library
  pointycastle: ^3.7.0

  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter
  qr_flutter: ^4.1.0

  # Quiver is a set of utility libraries for Dart that makes using many Dart libraries easier and more convenient, or adds additional functionality
  quiver: ^3.2.1

  # A flutter library that helps with http requests and stored cookies
  requests: ^4.7.0

  # A package exposing annotations for riverpod_generator
  riverpod_annotation: ^2.1.1

  # RxDart is an implementation of the popular reactiveX api for asynchronous programming, leveraging the native Dart Streams api.
  rxdart: ^0.27.7

  # Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  share_plus: ^6.3.0

  shelf: ^1.4.0
  shelf_router: ^1.1.3

  # Lock mechanism to prevent concurrent access to asynchronous code.
  socket_io_client: ^2.0.2
  synchronized: ^3.0.1

  # Tuple data structure
  tuple: ^2.0.1

  # Unicode 8.0 Normalization - NFC, NFD, NFKC, NFKD
  unorm_dart: ^0.2.0

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.1.10

  # String validation and sanitization for Dart
  validators: ^3.0.0

  # RPC server
  web_socket_channel: ^2.4.0

  # This plugin allows Flutter desktop apps to resizing and repositioning the window.
  window_manager: ^0.3.0

  # Yubico dart library for Dart/Flutter
  yubidart: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  # Integration Tests
  integration_test:
    sdk: flutter
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.0
  # A command-line tool that create Msix installer from your flutter windows-build files.
  msix: ^3.13.2
  # Simple yet powerful Flutter-native UI testing framework eliminating limitations of flutter_test, integration_test, and flutter_driver.
  patrol: ^1.1.4
  # A code generator for Riverpod. This both simplifies the syntax empowers it, such as allowing stateful hot-reload.
  riverpod_generator: ^2.2.3

msix_config:
  display_name: Archethic Wallet
  publisher_display_name: Archethic Technologies SARL
  identity_name: ArchethicTechnologiesSARL.ArchethicWallet
  publisher: CN=9687A561-7463-4BA7-BD4D-A04574BAF854
  msix_version: 2.1.437.0
  icons_background_color: "#000000"
  languages: en-us
  store: true
  logo_path: windows/icons/Icon-512.png
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: "internetClient,webcam,USB"

# The following section is specific to Flutter.
flutter:
  generate: true

  assets:
    - assets/ssl/isrg-root-x1.pem
    - assets/icons/
    - assets/icons/currency/
    - assets/icons/languages/
    - assets/icons/menu/
    - assets/icons/txInfos/
    - assets/buy/
    - assets/images/
    - assets/themes/sapphire_blue/
    - assets/themes/sapphire_blue_flat/
    - assets/themes/dark/
    - assets/themes/dark_flat/
    - assets/themes/emerald_green/
    - assets/themes/emerald_green_flat/
    - assets/themes/flat/
    - assets/themes/sea_green/
    - assets/themes/sea_green_flat/
    - assets/themes/navy_blue/
    - assets/themes/navy_blue_flat/
    - assets/themes/honey_orange/
    - assets/themes/honey_orange_flat/
    - assets/themes/byzantine_violet/
    - assets/themes/byzantine_violet_flat/
    - assets/themes/fire_red/
    - assets/themes/fire_red_flat/
    - assets/themes/pearl_grey/
    - assets/themes/pearl_grey_flat/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
    - family: Equinox
      fonts:
        - asset: assets/fonts/Equinox Bold.otf
        - asset: assets/fonts/Equinox Regular.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
    - family: UiIcons
      fonts:
        - asset: assets/fonts/ui_icons.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
