name: aewallet
description: AE Wallet App
version: 0.2.1+201
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core

  core_ui:
    path: ../core_ui

  aeuniverse:
    path: ../aeuniverse

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/
    - assets/icons/txInfos/
    - assets/buy/
