name: aeuniverse
description: AE Universe App
version: 0.2.0+200
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  aewallet:
    path: ../aewallet

  core:
    path: ../core

  core_ui:
    path: ../core_ui
    
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/apps/
    - assets/icons/
    - assets/icons/country/
    - assets/icons/currency/
    - assets/icons/txInfos/